### ISSUE TITLE
a11y icons

### ISSUE THREAD

**Issue by brianteeman** [joomla/Manual#15]
https://github.com/joomla/Manual/blob/406205673d55c2513d207119ddf35c005e093128/src/pages/index.js#L8

https://icons.getbootstrap.com/icons/universal-access/
or
https://icons.getbootstrap.com/icons/universal-access-circle/

**Comment by HLeithner** [comment]
Seems not to be included in react-icon set https://react-icons.github.io/react-icons/icons?name=bs

**Comment by brianteeman** [comment]
wow that icon set is massively out of date. they are using v1.5.0 and the current release is 1.9.1

**Comment by HLeithner** [comment]
Seems the BS icons are moving really fast https://github.com/twbs/icons/releases the universal access icon has been added 13.07.2022 anyway thanks for looking at it
