### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by brianteeman** [joomla/Manual#20]
I think this is an upstream issue but I couldn't find out where so I am just flagging it up for now as something to check

The search box generates code that includes the code
`aria-labelledby="autocomplete-0-label"`

There is no label of that name so this results in an invalid aria error

**Comment by HLeithner** [comment]
The label exists it's the button magnifying glass left to the input field
![image](https://user-images.githubusercontent.com/1497730/184853673-1bbcaeca-ff6b-4428-b917-0b4088b5437c.png)

it looks pretty much useless for a11y but maybe I'm wrong

**Comment by brianteeman** [comment]
strange

![image](https://user-images.githubusercontent.com/1296369/184861734-4956f922-c4d5-4d26-a179-5030b5b6f58a.png)

![image](https://user-images.githubusercontent.com/1296369/184862138-d18f8c7e-66cc-47c1-bd27-3e98d7ed93e4.png)

**Comment by brianteeman** [comment]
and the number keeps changing - very bizaar

**Comment by HLeithner** [comment]
It's this magnifying glass
![image](https://user-images.githubusercontent.com/1497730/184863281-b4d65d4c-008c-4523-9a7c-0dfda4d512a8.png)

and it only exists if you click on the button

so actually you are right there is no label as long as you didn't opened the search

we use https://github.com/cmfcmf/docusaurus-search-local maybe you can open an issue there?

**Comment by brianteeman** [comment]
ah - ok - I see what you mean now. I will raise an issue.

**Comment by brianteeman** [comment]
https://github.com/cmfcmf/docusaurus-search-local/issues/133
