### ISSUE TITLE
How to edit pages if I find an error or want to suggest an improvement?

### ISSUE THREAD

**Issue by rogercreagh** [joomla/Manual#264]
AT the bottom of each page is an "edit this page link" which takes me to this github.

If I want to suggest an imrovement or correct an error do I have to fork the whole doc repository and generate a pull request or is there a simpler quicker way?

**Comment by HLeithner** [comment]
yes that's the way to go, the manual has a full github workflow -> fork -> pr -> merge -> deploy

I hope your question is answered, I'm closing this. If you have questions, don't hesitate to ask.
