### ISSUE TITLE
Link colour in footer nearly invisible

### ISSUE THREAD

**Issue by chmst** [joomla/Manual#275]
![grafik](https://github.com/joomla/Manual/assets/1035262/9ae81bc2-5bdc-4286-8c77-ecbca5773ae5)

**Comment by rabahalishah** [comment]
@chmst Please assign me this issue. I am on it,

**Comment by rabahalishah** [comment]
@chmst I have made some possible changes without violating the color theme standards and made a PR. Kindly review it and let me know for further changes (if needed) Thank you! :)

**Comment by HLeithner** [comment]
solved, thanks @rabahalishah
