### ISSUE TITLE
Bulid Extensions/Modules Step 7 - Adding Javascript

### ISSUE THREAD

**Issue by pablop76** [joomla/Manual#336]
mod_hello/tmpl/default.php

...
$document = $app->getDocument();
...

it doesn't work!!!

$document = $this->app->getDocument();

it works

**Comment by HLeithner** [comment]
@robbiejackson can you have a look?

**Comment by robbiejackson** [comment]
Thanks for raising this issue - I've now fixed it.

**Comment by pablop76** [comment]
One more example https://manual.joomla.org/docs/building-extensions/modules/module-development-tutorial/step7-javascript/
"Our updated tmpl file is:"

**Comment by robbiejackson** [comment]
Ah, I didn't realise there were 2 lines to fix on each version. That's hopefully it sorted now.

Thanks again!
